---
all:
  children:
    balancer:
      hosts:
        nginx_balancer:
          ansible_ssh_host: 192.168.56.24
    webservers:
      hosts:
        nginx_1:
          ansible_ssh_host: 192.168.56.21
        nginx_2:
          ansible_ssh_host: 192.168.56.22
        nginx_3:
          ansible_ssh_host: 192.168.56.23
...