---
- name: Disable SWAP
  shell: swapoff -a

- name: Replacement in file /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install apt-transport-https ca-certificates gpg package
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - gpg
    - curl

# настройка статических ip адресов, имен и dns узлов кластера - скип

# добавление модулей ядра Linux для загрузки при запуске системы
# overlay - модуль файловой системы для создания слоев (для контейнеризации)
# br-netfilter - модуль для поддержки межстевого экрана (для фильтрации трафика на уровне ядра)

- name: Adding modules to config
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Add the overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

# # Разрешение маршрутизации IP-трафика
# - name: Allow IP traffic routing
#   ansible.builtin.copy:
#     dest: /etc/sysctl.d/10-k8s.conf
#     content: |
#       net.bridge.bridge-nf-call-ip6tables = 1
#       net.bridge.bridge-nf-call-iptables = 1
#       net.ipv4.ip_forward = 1

- name: Allow IP traffic routing and reboot system parameters
  sysctl:
    name: "{{item}}"
    value: '1'
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward


- name: Download the Release.key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /tmp/Release.key

# - name: Add kubernetes-apt-keyring GPG key
#   ansible.builtin.get_url:
#     url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
#     dest: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
#     mode: '0777'

- name: Add kubernetes-apt-keyring GPG key
  ansible.builtin.apt_key:
    file: /tmp/Release.key
    keyring: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    state: present

- name: Add k8s packages
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

- name: Remove Release.key
  ansible.builtin.file:
    path: /tmp/Release.key
    state: absent

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Install kubelet kubeadm kubectl
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Init kubeadm
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16

- name: Add environment variable to file
  ansible.builtin.copy:
    dest: /etc/environment
    content: export KUBECONFIG=/etc/kubernetes/admin.conf

- name: Add environment variable
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^KUBECONFIG="
    line: "KUBECONFIG=/etc/kubernetes/admin.conf"

- name: Kubectl apply
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Kubectl taint nodes
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
...